// Generated by gencpp from file file_server/GetBinaryFile.msg
// DO NOT EDIT!


#ifndef FILE_SERVER_MESSAGE_GETBINARYFILE_H
#define FILE_SERVER_MESSAGE_GETBINARYFILE_H

#include <ros/service_traits.h>


#include <file_server/GetBinaryFileRequest.h>
#include <file_server/GetBinaryFileResponse.h>


namespace file_server
{

struct GetBinaryFile
{

typedef GetBinaryFileRequest Request;
typedef GetBinaryFileResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetBinaryFile
} // namespace file_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::file_server::GetBinaryFile > {
  static const char* value()
  {
    return "e7a67f70bf777d8bfc72fa728a683c7d";
  }

  static const char* value(const ::file_server::GetBinaryFile&) { return value(); }
};

template<>
struct DataType< ::file_server::GetBinaryFile > {
  static const char* value()
  {
    return "file_server/GetBinaryFile";
  }

  static const char* value(const ::file_server::GetBinaryFile&) { return value(); }
};


// service_traits::MD5Sum< ::file_server::GetBinaryFileRequest> should match 
// service_traits::MD5Sum< ::file_server::GetBinaryFile > 
template<>
struct MD5Sum< ::file_server::GetBinaryFileRequest>
{
  static const char* value()
  {
    return MD5Sum< ::file_server::GetBinaryFile >::value();
  }
  static const char* value(const ::file_server::GetBinaryFileRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::file_server::GetBinaryFileRequest> should match 
// service_traits::DataType< ::file_server::GetBinaryFile > 
template<>
struct DataType< ::file_server::GetBinaryFileRequest>
{
  static const char* value()
  {
    return DataType< ::file_server::GetBinaryFile >::value();
  }
  static const char* value(const ::file_server::GetBinaryFileRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::file_server::GetBinaryFileResponse> should match 
// service_traits::MD5Sum< ::file_server::GetBinaryFile > 
template<>
struct MD5Sum< ::file_server::GetBinaryFileResponse>
{
  static const char* value()
  {
    return MD5Sum< ::file_server::GetBinaryFile >::value();
  }
  static const char* value(const ::file_server::GetBinaryFileResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::file_server::GetBinaryFileResponse> should match 
// service_traits::DataType< ::file_server::GetBinaryFile > 
template<>
struct DataType< ::file_server::GetBinaryFileResponse>
{
  static const char* value()
  {
    return DataType< ::file_server::GetBinaryFile >::value();
  }
  static const char* value(const ::file_server::GetBinaryFileResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FILE_SERVER_MESSAGE_GETBINARYFILE_H
