(cl:defpackage file_server-srv
  (:use )
  (:export
   "GETBINARYFILE"
   "<GETBINARYFILE-REQUEST>"
   "GETBINARYFILE-REQUEST"
   "<GETBINARYFILE-RESPONSE>"
   "GETBINARYFILE-RESPONSE"
   "GETFILE"
   "<GETFILE-REQUEST>"
   "GETFILE-REQUEST"
   "<GETFILE-RESPONSE>"
   "GETFILE-RESPONSE"
  ))

